### PR TITLE
Add the virtual keyboard protocol and use it

### PR DESCRIPTION
**Pull request by cceckman**
This lets you type with your voice!

Except that the keymap is all messed up so it won't type what you want. But it does type!

### CODE REVIEW

**Comment by livviest** [comment]
Looks like both `vosk-example.rs` and `consume.rs` have a hard-coded path for the vosk model causing the build to fail on any other machine. :)

```
tawaylon/src/bin/vosk-example.rs
12:    let model_path = "/home/cceckman/r/github.com/cceckman/tawaylon/models/vosk-small.dir";

tawaylon/src/bin/consume.rs
173:        let model_path = "/home/cceckman/r/github.com/cceckman/tawaylon/models/vosk-small.dir";
```

**Edit:** D'oh, I don't think I checked out this branch when I made this observation. Sorry.
**Edit edit:** Okay, I finally got a chance to checkout the correct branch and yes this is still a thing. Just wanted to make sure!

**Comment by cceckman** [comment]
> Looks like both `vosk-example.rs` and `consume.rs` have a hard-coded path for the vosk model causing the build to fail on any other machine. :)
> 
> ```
> tawaylon/src/bin/vosk-example.rs
> 12:    let model_path = "/home/cceckman/r/github.com/cceckman/tawaylon/models/vosk-small.dir";
> 
> tawaylon/src/bin/consume.rs
> 173:        let model_path = "/home/cceckman/r/github.com/cceckman/tawaylon/models/vosk-small.dir";
> ```
 
You're right of course :) I'll see about poking at it some next week!

**Comment by cceckman** [comment]
@ChrisRenfrow Pushed a fix; `redo tawaylon/run` if you have `redo` installed, `./do tawaylon/run` if you don't. Thanks for keeping me honest!

**Comment by livviest** [comment]
Ah yes it works now, very cool!

**Pull request merged**
